@server=http://localhost:4004
@username=alice
@password=


### Books
# @name Books_GET
GET {{server}}/browse/Books
Authorization: Basic {{username}}:{{password}}


### Currencies
# @name Currencies_GET
GET {{server}}/browse/Currencies
Authorization: Basic {{username}}:{{password}}


### CatalogService.submitOrder()
POST http://localhost:4004/browse/submitOrder
Content-Type: application/json
Authorization: Basic bob:

{
  "book": 201,
  "quantity": 3
}
